---
# - name: Install Packages and Prereqs for openssh server 
#   ansible.builtin.package:
#     name: openssh-server
#     state: present

# - name: Build sshd_config and put it in /etc/ssh
#   anible.builtin.template:
#     src:  sshd_config.j2
#     dest: /etc/ssh/sshd_config
#     owner:  root
#     group:  root
#     backup: yes
#     mode: 0644
#   notify: RestartSshd

- name: Add Custom Match rules to /etc/ssh/sshd_config.d
  ansible.builtin.template:
    src: Match_Rules.j2
    dest: /etc/ssh/sshd_config.d/09-MatchRules.conf
    owner: root
    group: root
    mode: 0444
  when: SshMatchRules|length > 0
# - name: is defined
  # debug:
  #   msg: "SshMatchRules is defined"
  # when: SshMatchRules|length > 0 
